{% set name = "smplotlib" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AstroJacobLi/smplotlib/releases/download/{{ version }}/smplotlib-{{ version }}.tar.gz
  url: https://github.com/AstroJacobLi/smplotlib/archive/v{{ version }}.tar.gz
  sha256: aadd11038f9fc6cc7d75626e9d6957150d039f3691c72546d3fab4641206b436

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42.0
    - wheel
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib>=3.3.4

test:
  imports:
    - smplotlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AstroJacobLi/smplotlib
  summary: Matplotlib template for SuperMongo style
  description: |
    A simple matplotlib template for SuperMongo style.
    Import the package and use matplotlib like usual. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/AstroJacobLi/smplotlib
  dev_url: https://github.com/AstroJacobLi/smplotlib

extra:
  recipe-maintainers:
    - AstroJacobLi
